### PR TITLE
sunxi: enable eDP bridge power on TERES I

### PR DESCRIPTION
**Pull request by Icenowy**
The TERES I DIY Laptop Kit uses the same ANX6345 eDP bridge with
Pinebook, but the 1.2V supply regulator is DLDO3 instead of FLDO1.

Setup power supplies for ANX6345 when the device is a TERES I (judged by
device tree).

Signed-off-by: Icenowy Zheng <icenowy@aosc.io>

### CODE REVIEW

**Comment by haraldg** [comment]
Hi, what is the status of this PR? Would be nice to have this merged, so that the atf-allwinner package in debian could support the Teres ...

**Comment by kilobyte** [comment]
@haraldg: strictly speaking, there's no requirement for any patch to be accepted upstream, it's merely highly preferred.  If your ping is because you'd want to hurry (rather than just to make sure this isn't forgotten), I can pick this immediately.

**Comment by haraldg** [comment]
On 02.04.2018 11:11, Adam Borowski wrote:
> @haraldg: strictly speaking, there's no requirement for any patch to
> be accepted upstream, it's merely highly preferred.  If your ping is
> because you'd want to hurry (rather than just to make sure this isn't
> forgotten), I can pick this immediately.

I'm in no hurry. It was suggested to me to write an 
InstallDebianOnTeres
wiki page and I thought that I check the status of upstreaming efforts
before and noticed that this PR is without comment for quite some time.

I guess to have debian installer support the laptop, we also need some
changes to u-boot merged and packages for debian. So this patch here
isn't the last missing piece anyway.

**Comment by apritzel** [comment]
@haraldg: I was waiting for some confirmation. Last time I checked the DT name in the PR was wrong (that seem to be fixed by now), also I wanted to wait till the DT (name) gets accepted in Linux. I see it in Maxime's tree now, so I guess we are good to go.
So can you confirm that this works for you? The schematic speaks of a 2ms delay between DLDO2 and DLDO3 setup, no idea how long the delay is in our case.

**Comment by haraldg** [comment]
On 02.04.2018 16:31, Andre Przywara wrote:
> @haraldg: I was waiting for some confirmation.

Ah, good to know ...

> So can you confirm that this works for you? The schematic speaks of a
> 2ms delay between DLDO2 and DLDO3 setup, no idea how long the delay 
> is
> in our case.

Yes, I was wondering about the delay too. The bootloader part of our
debian image was done by dddddd - I will ask about the details and
whether more tests are needed for this version of the patch.

I will come back to you after that.

**Comment by apritzel** [comment]
So I pushed a slightly amended version to the allwinner-testing branch. Please give it a try. Keep in mind that this requires to have the "sun50i-a64-teres-i" string in the SPL header.

**Comment by haraldg** [comment]
I can confirm, that the allwinner-testing branch works flawlessly on my
teres-i. Thanks.

**Comment by apritzel** [comment]
Pushed the commit to the allwinner branch.

**Pull request closed without merging**
