### PR TITLE
A64-uQ7 support and more reliable clock-setup

### PR DESCRIPTION
**Pull request by ptomsich**
Andre,

Here's the changes we have in our tree for the A64-uQ7 (Lynx).
Note that the changes to the init-sequence and clocking significantly improve the reliability of the boot process.

Cheers,
Philipp.

### CODE REVIEW

**Review by apritzel — COMMENTED** [review]
Is DCDC4 on per default on your board? The manual isn't clear about the reset state.
Also do you connect the DC5SET correctly (to VINT) on your board? In this case we should not need to actually program DCDC5. I do this just because the Pine64 got this obviously wrong (floating=1.24V instead of 1.36V). I changed my branch already to only correct from 1.24V to 1.36V to cover this case, which should work on any board (except for those using LPDDR3).
Also please add a comments about the DCDC4 enabling. 
And please understand that I can't merge this before we can somehow detect boards.

Thanks! Andre

**Review by apritzel — COMMENTED** [review]
That looks pretty good, but I need to digest the details first and merge it with my changes I made meanwhile.
Do you have an idea why we actually need to change the CPU clock source to LOSC for the change? This PLL should be able to do this while being live, right? At least this is my understanding of "supports dynamic frequency scaling" from the manual.

Thanks,
Andre.

**Comment by ptomsich** [comment]
Andre,

You may be right that we may not always have to switch away for PLL_CPUX and PLL_DDR1, as the manual states:
1)  In practical application, other PLLs doesn’t support dynamic frequency scaling except for PLL_CPUX and PLL_DDR1; 

I would nonetheless expect some level of instability on the PLL’s output that could glitch dependent clocks.
It’s not uncommon to support DVFS with a requirement to reparent during the transition time (for example, see drivers/cpufreq/imx6q-cpufreq.c for how it’s done on the i.MX6 which also supports DVFS).

The code in the linux-3.4 and -3.10 drops received with the A64 release doesn’t explicitly do this either, but boot0 still does.
As we don’t see the actual code that’s used in ARISC (we could disassemble and work our way through it, but it doesn’t appear worth it), I don’t know what Allwinner does on their end.
Given that there’s a difference between the PLL_CPUX and PLL_DDRx in that the PLL_DDRx have the PLL_DDR0_CFG_UPDATE/SDRPLL_UPD bits, I’d rather go with the conservative method of reparenting twice.

I’d vote to optimise later, but start with what we know is safe.

Cheers,
Phil.

**Comment by ptomsich** [comment]
DC5SET is defaulted to 1.5V as this is supported by both DDR3 and DDR3L.
We plan to update this to 1.36V whenever DDR3L is used (the default at the moment), based on the FDT contents.

As I mentioned, the changes to sunxi_power.c really need the FDT support to land before making sense...

**Comment by apritzel** [comment]
I merged the first two patches, while doing some cosmetic changes and dropping the (broken) CPU frequency print.
For the board specific setup, you could check out the sunxi64-beta U-Boot branch I just pushed on how to read the DT name from the SPL header to get the board name and do board specific setup tasks.

**Pull request closed without merging**
